common: &common
  username: postgres
  password: 

development:
  <<: *common
  database: avms2_development
  adapter: postgresql
  encoding: unicode
  pool: 25
  timeout: 5000

test: &test
  <<: *common
  database: avms2_test
  adapter: postgresql
  encoding: unicode
  pool: 25
  timeout: 5000

production:
  <<: *common

cucumber:
  <<: *test